### ISSUE TITLE
 Financial Advice Card

### ISSUE THREAD

**Issue by eben92** [rhutmann/nitro-dashboard#14]

**Comment by ishaanbedi** [comment]
Hey! Can you please provide a bit more details/descriptions of the issue?

**Comment by rhutmann** [comment]
The issue has been resolved 
But if you are willing to contribute on future/other issues, let me know I will provide more information on that for you. Thank you

**Comment by eben92** [comment]
> Hey! Can you please provide a bit more details/descriptions of the issue?

The issue has been resolved
But if you are willing to contribute on future/other issues, let me know I will provide more information on that for you. 

I was just putting up the issues and fixing them myself that's why I didn't provide any additional information or details.



Thank you.

**Comment by ishaanbedi** [comment]
Hey! I am a newbie to contribution and was looking for some projects to work on.
Still, do let me know of any future issue :)
